#pragma once
int  down = 40;
int  down1 = 40;
int  downend = 0;
int step = 0;
int step1 = 0;
int step2 = 0;
int step3 = 0;
int cc = 0;
int bb = 0;
int dd = 0;
int gg = 0;
int pointerrow;
int pointerrow2;
int pointercolumn;
int pointercolumn2;
bool check;
int key;
int attackrow;
int attackcolumn;
bool controller = true;
int lookingfor = 0;
int bUPlookingfor = 0;
int lookingforsecond = 0;
int bUPlookingforsecond = 0;
bool switCH1 = true;
bool switCH2 = true;
bool switCH3 = true;
bool switCH4 = true;
bool switCH5 = true;
bool switCH6 = true;
bool switCH7 = true;
bool switCH8 = true;
bool switCH9 = true;
bool switCH10 = true;
bool BswitCH1 = true;
bool BswitCH2 = true;
bool BswitCH3 = true;
bool BswitCH4 = true;
bool BswitCH5 = true;
bool BswitCH6 = true;
bool BswitCH7 = true;
bool BswitCH8 = true;
bool BswitCH9 = true;
bool BswitCH10 = true;
bool switchBIG1 = false;
bool switchBIG2 = false;
bool oneship1 = false;
bool oneship2 = false;
bool oneship3 = false;
bool oneship4 = false;
bool oneship5 = false;
bool oneship6 = false;
bool oneship7 = false;
bool oneship8 = false;
bool oneship9 = false;
bool oneship10 = false;
bool twoship1 = false;
bool twoship2 = false;
bool twoship3 = false;
bool twoship4 = false;
bool twoship5 = false;
bool twoship6 = false;
bool twoship7 = false;
bool twoship8 = false;
bool twoship9 = false;
bool twoship10 = false;
int limitofship4 = 1;
int limitofship3 = 2;
int limitofship2 = 3;
int limitofship1 = 4;
int manualship4coordinantROW;
int manualship4coordinantCOLUMN;
bool manualship4coordinantA = false;
int manual1ship3coordinantROW;
int manual1ship3coordinantCOLUMN;
bool manual1ship3coordinantA = false;
int manual2ship3coordinantROW;
int manual2ship3coordinantCOLUMN;
bool manual2ship3coordinantA = false;
int manual1ship2coordinantROW;
int manual1ship2coordinantCOLUMN;
bool manual1ship2coordinantA = false;
int manual2ship2coordinantROW;
int manual2ship2coordinantCOLUMN;
bool manual2ship2coordinantA = false;
int manual3ship2coordinantROW;
int manual3ship2coordinantCOLUMN;
bool manual3ship2coordinantA = false;
int manual1ship1coordinantROW;
int manual1ship1coordinantCOLUMN;
bool manual1ship1coordinantA = false;
int manual2ship1coordinantROW;
int manual2ship1coordinantCOLUMN;
bool manual2ship1coordinantA = false;
int manual3ship1coordinantROW;
int manual3ship1coordinantCOLUMN;
bool manual3ship1coordinantA = false;
int manual4ship1coordinantROW;
int manual4ship1coordinantCOLUMN;
bool manual4ship1coordinantA = false;
bool comebacktogame = false;






